### ISSUE TITLE
The links on http://oboejs.com/ are broken

### ISSUE THREAD

**Issue by isaksky** [jimhigson/oboe.js-website#15]
None of the links work. They are all like this:

![image](https://cloud.githubusercontent.com/assets/607986/12563424/80aa0e8c-c367-11e5-8bdd-c939732b1422.png)

http://oboejs.com/examples
http://oboejs.com/why

**Comment by JuanCaicedo** [comment]
As in if you click both of those links you just posted, they don't work? I'm able to go to both without a problem

**Comment by isaksky** [comment]
Yeah. I checked my mobile, and it works from there, so now I don't know. Maybe there is an error with my work network. I'll check at home later in the day.

**Comment by isaksky** [comment]
It works at home too. Guess it was just a strange network problem.
