### ISSUE TITLE
Did you loose the domain oboejs.com?

### ISSUE THREAD

**Issue by fraguada** [jimhigson/oboe.js-website#17]
Seems it is now pointing elsewhere.
![screen shot 2016-03-16 at 16 56 29](https://cloud.githubusercontent.com/assets/1014562/13818961/28baeb7a-eb98-11e5-8328-2aec97531287.png)

**Comment by jimhigson** [comment]
Hmmm... will look into this. SHouldn't have lost the domain.

**Comment by jimhigson** [comment]
Looks like a bug in nodejitsu. I restarted the app on there and it works again.

Will need to migrate away from jitsu I think. Thanks for pointing this out. Have also contacted the email address on that page to ask if they know why the apps are overlapping on jitsu.

**Comment by JuanCaicedo** [comment]
Yeah, this is really crazy. I can prioritize trying to migrate to a gh-pages version after this weekend.

**Comment by jimhigson** [comment]
That would be awesome. I looked at the headers on http://liefdraws.com and doesn't even seem to be hosted on node - looks like Apache.

Will also ask someone that I know at nodejitsu to take a look, but hard to believe they are accidentally re-rooting to an app that they don't host.

Very strange.

**Comment by jimhigson** [comment]
It happened again today, just restarted it again.

Time to transition then as soon as I find a little time:
https://www.nodejitsu.com/documentation/nodejitsu-modulus-transition/

**Comment by nhducit** [comment]
Sometime I cannot access to oboe home page. It shows a node jitsu error page.

**Comment by nhducit** [comment]
It require username and pass word when I access to oboe home page 
![screenshot from 2016-03-22 14-26-49](https://cloud.githubusercontent.com/assets/4246176/13944695/005f5930-f03a-11e5-8775-546568f82193.png)

**Comment by catmeme** [comment]
I'm getting this error as well.

**Comment by JuanCaicedo** [comment]
@catmeme thanks for reporting! This error is off and on, unfortunately I don't think @jimhigson was able to fix it in nodejitsu. 

I have a project underway for moving this to gh-pages. https://github.com/jimhigson/oboe.js-website/issues/20. Hopefully that will be up and functioning soon!

In the mean time, for anyone looking to read the docs, feel free to:

```bash
$ git clone https://github.com/jimhigson/oboe.js-website.git
$ cd oboe.js-website/
$ npm install
$ grunt start-dev
```

Then you should be able to go to http://localhost:8888/ and view the site

**Comment by catmeme** [comment]
@JuanCaicedo Thanks, glad to hear progress is being made, the migration to gh-pages is a good move.

Unfortunately cloning and running locally won't work for my use case. I was trying to show my coworkers those pretty diagrams that describe what oboe.js is and how it works.

I'll wait until the migration is complete to share with them.

Cheers.

**Comment by JuanCaicedo** [comment]
Something you could try that worked for me:

- Go to https://www.oboejs.com/
- You should see a security warning (in Chrome)
- Click Adcanced > Proceed anyway
- Look at the site! (maybe)

**Comment by catmeme** [comment]
Thanks, I appreciate your efforts :)

**Comment by JuanCaicedo** [comment]
Oboe website is up and @jimhigson has moved the hosting over to heroku, which I think should solve troubles we were having

**Comment by catmeme** [comment]
FYI https still throws a privacy error in Chrome

**Comment by JuanCaicedo** [comment]
@catmeme great point thank you! Given that Google penalizes sites that only use http, I think this is worth fixing
